'use client'
// Payment recording, receipts, payment history and reversal requests
import { useEffect, useState } from 'react'
import { useAuthStore } from '@/hooks/useAuth'
import {
  call, errorText, money, fmtDate, today, METHOD_LABELS,
  S, Banner, Pill, Field, Modal, statusTone,
} from './ui'

export interface FeeItem { id: string; name: string; amount: number; is_mandatory?: boolean }
export interface StudentRef { id: string; full_name: string; admission_no?: string | null; class_level?: string | null; class_arm?: string | null }

export interface ReceiptData {
  receiptNo: string
  studentName: string
  admissionNo?: string | null
  className?: string
  feeName: string
  amount: number
  method: string
  reference?: string | null
  date: string
  payerName?: string | null
  recordedBy?: string
}

// ── Printable receipt (opens a clean window and prints it) ──────────────────
export function printReceipt(r: ReceiptData, schoolName: string) {
  const w = window.open('', '_blank', 'width=640,height=720')
  if (!w) return
  const esc = (s: any) => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string))
  const row = (k: string, v: any) => v ? `<tr><td class="k">${esc(k)}</td><td>${esc(v)}</td></tr>` : ''
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Receipt ${esc(r.receiptNo)}</title>
  <style>
    body{font-family:system-ui,Arial,sans-serif;color:#1a1a18;padding:32px;max-width:560px;margin:auto}
    h1{font-size:20px;margin:0}h2{font-size:14px;font-weight:600;color:#6b6b65;margin:4px 0 24px}
    .no{font-size:13px;color:#6b6b65}.amt{font-size:28px;font-weight:700;margin:16px 0;color:#0f4a32}
    table{width:100%;border-collapse:collapse;font-size:14px}td{padding:8px 0;border-bottom:1px solid #eee}
    td.k{color:#6b6b65;width:40%}.foot{margin-top:32px;font-size:12px;color:#a0a09a}
    @media print{button{display:none}}
  </style></head><body>
  <h1>${esc(schoolName)}</h1><h2>Official Fee Receipt</h2>
  <div class="no">Receipt No: <strong>${esc(r.receiptNo)}</strong> &nbsp;·&nbsp; ${esc(fmtDate(r.date))}</div>
  <div class="amt">${esc(money(r.amount))}</div>
  <table>
    ${row('Student', r.studentName)}${row('Admission No', r.admissionNo)}${row('Class', r.className)}
    ${row('Fee item', r.feeName)}${row('Payment method', METHOD_LABELS[r.method] ?? r.method)}
    ${row('Reference', r.reference)}${row('Paid by', r.payerName)}${row('Received by', r.recordedBy)}
  </table>
  <p class="foot">Generated by Examify. Keep this receipt for your records.</p>
  <button onclick="window.print()" style="margin-top:16px;padding:8px 16px">Print</button>
  <script>setTimeout(function(){window.print()},300)</script>
  </body></html>`)
  w.document.close()
}

// ── Record a manual payment ──────────────────────────────────────────────────
export function PaymentForm({ student, termId, feeItems, defaultFeeId, balances, onDone, onCancel }: {
  student: StudentRef
  termId: string
  feeItems: FeeItem[]
  defaultFeeId?: string
  balances?: Record<string, number>   // feeId -> amount still owed on that item
  onDone: (receipt: ReceiptData) => void
  onCancel?: () => void
}) {
  const { user } = useAuthStore()
  // Default to the first item that still has something owing
  const firstOwing = () => defaultFeeId ?? feeItems.find(f => (balances?.[f.id] ?? 1) > 0)?.id ?? feeItems[0]?.id ?? ''
  const [feeId, setFeeId] = useState(firstOwing())
  const [touched, setTouched] = useState(false)
  const [amount, setAmount] = useState('')
  const [method, setMethod] = useState('cash')
  const [reference, setReference] = useState('')
  const [date, setDate] = useState(today())
  const [payerName, setPayerName] = useState('')
  const [payerBank, setPayerBank] = useState('')
  const [notes, setNotes] = useState('')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  // Re-pick when items/balances arrive, unless the user has chosen an item themselves
  const balanceKey = balances ? JSON.stringify(balances) : ''
  useEffect(() => {
    if (!touched || !feeItems.some(f => f.id === feeId)) setFeeId(firstOwing())
  }, [feeItems, balanceKey])

  const needsRef = method !== 'cash'
  const fee = feeItems.find(f => f.id === feeId)
  const owing = balances && feeId in balances ? balances[feeId] : null

  async function submit() {
    setError('')
    const amt = parseFloat(amount)
    if (!feeId) { setError('Choose the fee item being paid.'); return }
    if (!amt || amt <= 0) { setError('Enter the amount received.'); return }
    if (needsRef && !reference.trim()) { setError('Enter the teller, transfer or POS reference.'); return }
    if (owing !== null && amt > owing) {
      const msg = owing <= 0
        ? `${fee?.name ?? 'This item'} is already fully paid. Record ${money(amt)} against it anyway?`
        : `${money(amt)} is more than the ${money(owing)} still owed on ${fee?.name ?? 'this item'}. Record it anyway?`
      if (!confirm(msg)) return
    }
    setSaving(true)
    try {
      const r = await call('/fees/payments', {
        method: 'POST',
        body: JSON.stringify({
          feeStructureId: feeId, studentId: student.id, amountPaid: amt, paymentMethod: method,
          paymentDate: date, transferReference: reference.trim() || undefined,
          payerName: payerName || undefined, payerBank: payerBank || undefined, notes: notes || undefined,
        }),
      })
      if (!r.ok) { setError(errorText(r.data)); return }
      onDone({
        receiptNo: r.data.receiptNo, studentName: student.full_name, admissionNo: student.admission_no,
        className: [student.class_level, student.class_arm].filter(Boolean).join(' '),
        feeName: fee?.name ?? '', amount: amt, method, reference: reference.trim() || null,
        date, payerName: payerName || null, recordedBy: user?.fullName,
      })
    } catch { setError('Network error. Please try again.') } finally { setSaving(false) }
  }

  return (
    <div>
      <p style={{ fontSize: '0.875rem', color: '#3a3a36', marginBottom: '1rem' }}>
        <strong>{student.full_name}</strong>{student.admission_no ? ` · ${student.admission_no}` : ''}
        {student.class_level ? ` · ${student.class_level}${student.class_arm ? ' ' + student.class_arm : ''}` : ''}
      </p>
      {!termId && <Banner tone="warning">Select a term first.</Banner>}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.875rem', marginBottom: '0.875rem' }}>
        <div style={{ gridColumn: '1 / -1' }}>
          <Field label="Fee item">
            <select style={S.input} value={feeId} onChange={e => { setFeeId(e.target.value); setTouched(true) }}>
              {feeItems.length === 0 && <option value="">No fee items for this class/term</option>}
              {feeItems.map(f => {
                const b = balances?.[f.id]
                let tail = ''
                if (b !== undefined) tail = b > 0 ? ` · ${money(b)} owing` : ' · paid'
                return <option key={f.id} value={f.id}>{f.name} — {money(f.amount)}{tail}</option>
              })}
            </select>
          </Field>
        </div>
        <Field label="Amount received (₦)" hint={owing !== null ? (owing > 0 ? `Still owed on this item: ${money(owing)}` : 'This item is fully paid.') : undefined}>
          <input style={S.input} type="number" min="0" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" />
        </Field>
        <Field label="Payment date">
          <input style={S.input} type="date" value={date} max={today()} onChange={e => setDate(e.target.value)} />
        </Field>
        <Field label="Method">
          <select style={S.input} value={method} onChange={e => setMethod(e.target.value)}>
            <option value="cash">Cash</option>
            <option value="bank_transfer">Bank transfer / teller</option>
            <option value="pos">POS</option>
            <option value="cheque">Cheque</option>
          </select>
        </Field>
        <Field label={needsRef ? 'Reference (required)' : 'Reference (optional)'} hint="Teller no., transfer ref. or POS slip no.">
          <input style={S.input} value={reference} onChange={e => setReference(e.target.value)} />
        </Field>
        <Field label="Paid by (optional)">
          <input style={S.input} value={payerName} onChange={e => setPayerName(e.target.value)} placeholder="e.g. Mrs Adeyemi" />
        </Field>
        <Field label="Payer's bank (optional)">
          <input style={S.input} value={payerBank} onChange={e => setPayerBank(e.target.value)} />
        </Field>
        <div style={{ gridColumn: '1 / -1' }}>
          <Field label="Notes (optional)">
            <input style={S.input} value={notes} onChange={e => setNotes(e.target.value)} />
          </Field>
        </div>
      </div>
      {error && <Banner tone="error">{error}</Banner>}
      <div style={{ display: 'flex', gap: '0.6rem', justifyContent: 'flex-end' }}>
        {onCancel && <button style={S.btnGhost} onClick={onCancel}>Cancel</button>}
        <button style={{ ...S.btn, opacity: saving ? 0.6 : 1 }} disabled={saving || !termId} onClick={submit}>
          {saving ? 'Saving…' : 'Record payment'}
        </button>
      </div>
    </div>
  )
}

// ── Receipt confirmation card ────────────────────────────────────────────────
export function ReceiptCard({ receipt, onClose }: { receipt: ReceiptData; onClose?: () => void }) {
  const { user } = useAuthStore()
  return (
    <Banner tone="success" onClose={onClose}>
      <strong>Payment recorded.</strong> Receipt <strong>{receipt.receiptNo}</strong> · {receipt.studentName} · {money(receipt.amount)}
      <div style={{ marginTop: '0.5rem' }}>
        <button style={S.btnSmall} onClick={() => printReceipt(receipt, user?.school?.name ?? '')}>🖨️ Print receipt</button>
      </div>
    </Banner>
  )
}

// ── One student's payment history, with "request reversal" ──────────────────
export function PaymentHistory({ student, termId, canWrite, onChanged }: {
  student: StudentRef; termId: string; canWrite: boolean; onChanged?: () => void
}) {
  const { user } = useAuthStore()
  const [rows, setRows] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [reversing, setReversing] = useState<any | null>(null)
  const [reason, setReason] = useState('')
  const [msg, setMsg] = useState<{ tone: 'success' | 'error'; text: string } | null>(null)
  const [saving, setSaving] = useState(false)

  async function load() {
    setLoading(true)
    const q = new URLSearchParams({ studentId: student.id })
    if (termId) q.set('termId', termId)
    const r = await call(`/fees/payments?${q}`)
    setRows(r.data.payments ?? [])
    setLoading(false)
  }
  useEffect(() => { load() }, [student.id, termId])

  async function submitReversal() {
    if (reason.trim().length < 10) { setMsg({ tone: 'error', text: 'Give a clear reason (at least 10 characters).' }); return }
    setSaving(true)
    const r = await call('/finance/reversals', { method: 'POST', body: JSON.stringify({ paymentId: reversing.id, reason: reason.trim() }) })
    setSaving(false)
    if (!r.ok) {
      let text = errorText(r.data)
      if (r.data.error === 'ALREADY_REVERSED_OR_PENDING') text = 'A reversal for this receipt is already pending or approved.'
      setMsg({ tone: 'error', text }); return
    }
    setMsg({ tone: 'success', text: `Reversal requested for ${reversing.receipt_number}. It takes effect once approved.` })
    setReversing(null); setReason('')
    onChanged?.()
  }

  return (
    <div>
      {msg && <Banner tone={msg.tone} onClose={() => setMsg(null)}>{msg.text}</Banner>}
      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead><tr>
          <th style={S.th}>Date</th><th style={S.th}>Receipt</th><th style={S.th}>Fee</th>
          <th style={S.th}>Method</th><th style={{ ...S.th, ...S.num }}>Amount</th><th style={S.th}></th>
        </tr></thead>
        <tbody>
          {loading ? <tr><td colSpan={6} style={{ ...S.td, color: '#6b6b65' }}>Loading…</td></tr>
            : rows.length === 0 ? <tr><td colSpan={6} style={{ ...S.td, color: '#6b6b65' }}>No payments this term.</td></tr>
            : rows.map(p => (
              <tr key={p.id} style={{ opacity: p.is_reversed ? 0.55 : 1 }}>
                <td style={S.td}>{fmtDate(p.payment_date)}</td>
                <td style={S.td}>{p.receipt_number} {p.is_reversed && <Pill tone="error">Reversed</Pill>}</td>
                <td style={S.td}>{p.fee_name}</td>
                <td style={S.td}>{METHOD_LABELS[p.payment_method] ?? p.payment_method}</td>
                <td style={{ ...S.td, ...S.num, textDecoration: p.is_reversed ? 'line-through' : 'none' }}>{money(p.amount_paid)}</td>
                <td style={{ ...S.td, textAlign: 'right' }}>
                  <div style={{ display: 'flex', gap: '0.35rem', justifyContent: 'flex-end' }}>
                    {!p.is_reversed && (
                      <button style={S.btnSmall} onClick={() => printReceipt({
                        receiptNo: p.receipt_number, studentName: student.full_name, admissionNo: student.admission_no,
                        className: [student.class_level, student.class_arm].filter(Boolean).join(' '),
                        feeName: p.fee_name, amount: Number(p.amount_paid), method: p.payment_method, date: p.payment_date,
                      }, user?.school?.name ?? '')}>Receipt</button>
                    )}
                    {canWrite && !p.is_reversed && (
                      <button style={S.btnDanger} onClick={() => { setReversing(p); setReason(''); setMsg(null) }}>Request reversal</button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
        </tbody>
      </table>

      {reversing && (
        <Modal title="Request a reversal" onClose={() => setReversing(null)}>
          <p style={{ fontSize: '0.86rem', color: '#3a3a36', marginBottom: '0.75rem' }}>
            Receipt <strong>{reversing.receipt_number}</strong> · {money(reversing.amount_paid)} · {reversing.fee_name}
          </p>
          <Banner tone="info">Reversals always need the Proprietor's approval. The receipt stays on record, marked as reversed, and the amount is added back to the student's balance once approved.</Banner>
          <Field label="Reason">
            <textarea style={{ ...S.input, minHeight: 80 }} value={reason} onChange={e => setReason(e.target.value)} placeholder="e.g. Teller bounced at the bank; recorded against the wrong student" />
          </Field>
          <div style={{ display: 'flex', gap: '0.6rem', justifyContent: 'flex-end', marginTop: '1rem' }}>
            <button style={S.btnGhost} onClick={() => setReversing(null)}>Cancel</button>
            <button style={{ ...S.btn, background: '#b91c1c', opacity: saving ? 0.6 : 1 }} disabled={saving} onClick={submitReversal}>
              {saving ? 'Sending…' : 'Send for approval'}
            </button>
          </div>
        </Modal>
      )}
    </div>
  )
}

export function StatusPill({ status }: { status: string }) {
  return <Pill tone={statusTone(status)}>{status.charAt(0).toUpperCase() + status.slice(1)}</Pill>
}
